### PR TITLE
Add a release checklist

### PR DESCRIPTION
**Pull request by jrfnl**
... to document the release process and as a reminder for the future.

### CODE REVIEW

**Comment by ozh** [comment]
Does this file then get automatically displayed somewhere as a prefilled template ?

**Comment by jrfnl** [comment]
> Does this file then get automatically displayed somewhere as a prefilled template ?

No, it does not. Unless it has changed without me noticing, AFAIK you can have multiple issue templates, but only one (1) PR template.
With that in mind, it's not useful to set it up as a PR template as it would just confuse people, but having it available in the `.github` directory still makes it easy to access it and copy/paste the content to a release issue for maintainers.

And independently of the template part of it, it is also a way to just document the steps for doing a release.

**Comment by schlessera** [comment]
For WP-CLI, I've added the release check list as an issue template which can be generated (see the last two entries): https://github.com/wp-cli/wp-cli/issues/new/choose

**Comment by jrfnl** [comment]
@schlessera Will have a look and update over the weekend.

**Comment by ozh** [comment]
You guys have seen this : https://probot.github.io/apps/release-drafter/ ?

**Comment by jrfnl** [comment]
@ozh My experience with any type of changelog generators is absolutely lousy. They create technical changelogs based on PR titles, which in most cases are completely useless for end-users.

Case in point from this week: https://github.com/gitextensions/gitextensions/blob/release/3.5/GitUI/Resources/ChangeLog.md

That release contained at least two breaking changes ([gitextensions#9112](https://github.com/gitextensions/gitextensions/issues/9112) and [gitextensions#9113](https://github.com/gitextensions/gitextensions/issues/9113)). Aside from the fact that those shouldn't have been allowed to go into a minor, they also weren't mentioned in the changelog and finding the PR which caused them meant having to go through 100+ PRs to see if I could figure it out. I found the cause of one, but not the other.

Yes, it's a pain in the neck having to write up a changelog, but the pain in the neck for end-users being confronted by an absolutely useless PR list is much larger.

**Comment by jrfnl** [comment]
> For WP-CLI, I've added the release check list as an issue template which can be generated (see the last two entries): 

@schlessera I've had a look at this, but that would make it an issue template, while it is (was) intended as a PR template for the `develop` to `master` merge PR.

**Comment by ozh** [comment]
FWIW, here's how I do it for YOURLS (infrequent releases so I was always forgetting what's to be done) : I have a draft release that I use as a template and copy/paste everytime then fill, with inline HTML comment helper. Impossible to miss since it's the first thing I see on the relase page when I want to tag a new one :)

Release page:

image

Source : 

image

**Review by schlessera — APPROVED** [review]

**Pull request merged**
