### PR TITLE
add support proxy for curl multirequest

### PR DESCRIPTION
**Pull request by Cosolom**

### CODE REVIEW

**Comment by texnixe** [comment]
This PR actually fixes a problem I currently have with a multirequest and proxy. Are there any plans to fix this issue otherwise (couldn't find a related issue)? Because this PR has been lying around open for almost four years now…

**Comment by jrfnl** [comment]
@texnixe Hi Sonja, this project has seen little action in the past few years, though a few of us have been trying to revive it recently.
We've been working through some of the most urgent backlogs first, but intend to do one or more public triage sessions in the near future to go through everything else which is still open. Also see #460.

You are very welcome to join us in those sessions and to contribute to the project.

As for this particular ticket, this change needs a unit test to accompany it. If would be great if you could provide one, so this PR will become eligible for merging.

**Comment by jrfnl** [comment]
@Cosolom @texnixe  Hiya! Sorry for the long wait, but we're finally trying to get through the list of open PRs.

We're currently planning two triage sessions for Requests 2.0 and would like to invite you to join us in one or both of these sessions to talk us through the PR and discuss it.

The triage sessions are currently planned for:
* Friday August 20, 07:00 - 11:00 UTC
* Friday September 3, 07:00 - 11:00 UTC

Would you be available to join us during those times on one of those days ?

Also: would you be willing and able to add some tests for these changes to the PR ?

**Comment by schlessera** [comment]
I will look into adding a test for this to get it into a mergeable state.

**Comment by jrfnl** [comment]
Closing as merged via #667 (with test).

**Pull request closed without merging**
