### PR TITLE
Update certificates file to latest version as of 2021-02-12

### PR DESCRIPTION
**Pull request by schlessera**
Certificate data from Mozilla as of: `Tue Jan 19 04:12:04 2021 GMT`
SHA256: `3bdc63d1de27058fec943a999a2a8a01fcc6806a611b19221a7727d3d9bbbdfd`

### Added

- `NAVER Global Root Certification Authority`

### Removed

- `GeoTrust Global CA`
- `GeoTrust Universal CA`
- `GeoTrust Universal CA 2`
- `GeoTrust Primary Certification Authority`
- `GeoTrust Primary Certification Authority - G3`
- `thawte Primary Root CA`
- `thawte Primary Root CA - G2`
- `thawte Primary Root CA - G3`
- `VeriSign Class 3 Public Primary Certification Authority - G4`
- `VeriSign Class 3 Public Primary Certification Authority - G5`

#### Re-added for legacy reasons

(by cross-referencing https://core.trac.wordpress.org/ticket/34935#comment:10 with https://core.trac.wordpress.org/browser/trunk/src/wp-includes/certificates/ca-bundle.crt)
- `Thawte Server CA`
- `Thawte Premium Server CA`
- `Verisign Class 3 Public Primary Certification Authority`
- `Verisign Class 3 Public Primary Certification Authority - G2`

### CODE REVIEW

**Comment by schlessera** [comment]
@dd32, @soulseekah The above is based on my best guess on how to handle an update to the certificates file to both keep current with the latest state of Mozilla and keep required legacy 1024-bit certificates.

Thoughts on whether these 1024-bit certificates are still needed?

**Comment by schlessera** [comment]
Note: We're about to push a new release v1.7.1 for Requests (the first since 2016), so we'd appreciate any testing that can be done on this.

**Comment by todeveni** [comment]
> Thawte Server CA
> Thawte Premium Server CA

These have expired in 2021-01-01, see https://www.thawte.com/roots/retired.html

**Review by jrfnl — APPROVED** [review]
The hosting team has been asked for feedback, but hasn't left any.

Taking all the research into account, this seems like a good change.

**Pull request merged**
